# Generated by Django 3.2.22 on 2023-10-23 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_message', models.TextField()),
                ('contact_submitted_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-contact_submitted_on'],
            },
        ),
    ]
